name: Deploy to TencentCloud

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
          matrix:
            node-version: [20]
        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 10
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Build website
              run: pnpm build

            - name: Install coscmd
              run: sudo pip install coscmd
            - name: Configure coscmd
              env:
                SECRET_ID: ${{ secrets.SecretId }}
                SECRET_KEY: ${{ secrets.SecretKey }}
                BUCKET: hsio-website-1301015343
                REGION: ap-shanghai
              run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
            - name: Upload
              run: coscmd upload -rfs --delete build/ /

            - name: Install tccli
              run: sudo pip install tccli 
            - name: Configure tccli secretId
              run: tccli configure set secretId ${{ secrets.SecretId }}
            - name: Configure tccli secretKey 
              run: tccli configure set secretKey ${{ secrets.SecretKey }}
            - name: Flush CDN@CN
              run: tccli teo CreatePurgeTask --cli-unfold-argument --ZoneId zone-37925m4imngy --Type purge_host --Method invalidate --Targets 'https://www.hosimiyasio.com/'